### ISSUE TITLE
parse_theorem_seqs

### ISSUE THREAD

**Issue by Maksonch11k** [FormalGeo/FormalGeo#1]
Hi, when i use 
for t_name, t_branch, t_para in parse_theorem_seqs(problem_CDL["theorem_seqs"]): solver.apply_theorem(t_name, t_branch, t_para)
it return exception "NameError: name 'parse_theorem_seqs' is not defined"

**Comment by BitSecret** [comment]
import this func: `from formalgeo.parse import parse_theorem_seqs`
