### ISSUE TITLE
How to add problem

### ISSUE THREAD

**Issue by Maksonch11k** [FormalGeo/FormalGeo#2]
Hi, do you have instructions on how to add your own problems to the dataset so that FormalGeo will try to solve them? 
thanks in advance

**Comment by BitSecret** [comment]
The documentation for formalgeo is not yet complete, so you might want to read the source code to learn more about how to use its functions. 
All information required by the solver can be input through a json file. You can refer to the format of GDL and CDL in the datasets folder, and then personalize your own formal system. The default download location for the datasets is the installation location of FormalGeo.
GDL (Geometric definition language)  includes predicate definition language and theorem definition language. Before solving the problem, the GDL is input into the solver to configure the formalization system of the solver. These two files are located in "your_datasets_path/formalgeo7k/gdl".
CDL (Condition Declaration Language) is used for the input of geometric problems. Example problems are located in "your_datasets_path/formalgeo7k/problems".

```
from formalgeo.tools import load_json

predicate_gdl = load_json("your_datasets_path/formalgeo7k/gdl/predicate_GDL")
theorem_gdl = load_json("your_datasets_path/formalgeo7k/gdl/theorem_GDL")
problem_cdl = load_json("your_datasets_path/formalgeo7k/problems/1.json")
```

The above are all the inputs required for the solver to run. Then load formal system and problem:

```
from formalgeo.solver import Interactor

solver = Interactor(predicate_gdl, theorem_gdl)
solver.load_problem(problem_cdl)
```

Then, you can input theorems and run interactively to solve the problem.

```
from formalgeo.solver import Interactor
from formalgeo.parse import parse_one_theorem
from formalgeo.tools import show_solution

solver = Interactor(predicate_gdl, theorem_gdl)
solver.load_problem(problem_cdl)
while not solver.problem.goal.solved:
    t_name, t_branch, t_para = parse_one_theorem(input("input theorem:"))
    solver.problem.check_goal()
    show_solution(solver.problem)
```
